embedding_size: 128              # (int) The embedding size of users and items.
n_layers: 2                     # (int) The number of layers in LightGCN.
reg_weight: 1e-05               # (float) The L2 regularization weight.
input_dim: 128
metrics: ["Recall","MRR","NDCG","Hit","Precision","SAE_Loss_i", "SAE_Loss_u", "SAE_Loss_total", "Gini", "Deep_LT_Coverage", "GiniIndex", "TailPercentage", "AveragePopularity", "ItemCoverage"]  # (list or str) Evaluation metrics.



analyze: False
sae_k: [8, 8]
sae_scale_size: [32, 32]
learning_rate:  1e-3
valid_metric: SAE_Loss_total
N: [4096, 4096]
alpha: [0.0, 0.0]
steer: [0, 0]